# Generated by Django 4.2.27 on 2026-03-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("weightlifting", "Weightlifting"),
                            ("tae_bo", "Tae Bo"),
                            ("running", "Running"),
                            ("cycling", "Cycling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Total time spent in minutes"
                    ),
                ),
                ("calories_burned", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="How did the workout feel?"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_name",
                    models.CharField(
                        help_text="E.g., Barbell Squat, Overhead Press", max_length=100
                    ),
                ),
                ("set_number", models.PositiveIntegerField(default=1)),
                ("reps", models.PositiveIntegerField()),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight lifted (kg/lbs)",
                        max_digits=6,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sets",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["activity", "set_number"],
            },
        ),
    ]
